core/urls.py
from django.urls import path

from core.views import index

urlpatterns = [
    path('', index, name='index')
]

kheylisadas/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from kheylisadas import settings
from .views import home_page, header, footer, index_page, success_page, failure_page, maintenance_view, service_worker, \
    manifest_version, check_login_status

urlpatterns = [
    path('maintenance/', maintenance_view, name='maintenance'),
    # path('index', index_page, name="home_page"),
    path('', home_page, name="home_page"),
    path('index', home_page, name="home_page"),
    path('success', success_page, name="success_page"),
    path('failure', failure_page, name="failure_page"),
    path('service-worker/', service_worker, name='service-worker'),
    path('manifest-version/', manifest_version, name='manifest_version'),
    path('check-login-status/', check_login_status, name='check_login_status'),

    path('', include('ks_account.urls')),
    path('', include('ks_category.urls')),
    path('audio/', include('ks_audio.urls')),
    path('courses/', include('ks_course.urls')),
    path('articles/', include('ks_article.urls')),
    path('subscription/', include('ks_subscription.urls')),
    path('votes/', include('ks_vote.urls')),
    path('user/', include('ks_user_panel.urls')),
    path('', include('ks_site.urls')),
    path('header', header, name="header"),
    path('footer', footer, name="footer"),
    path('ks-admin-panel/', admin.site.urls),
    path('ks-account/', include(('ks_account.urls', 'ks_account'), namespace='ks_account')), # اضافه کردن namespace
    # path('admin/', admin.site.urls),
    path('core/', include('core.urls')),  # for webpack
    path('captcha/', include('captcha.urls')),  # capthca urls
    # path('ckeditor/', include('ckeditor_uploader.urls')),  # ckeditor uploader urls
    path('ckeditor/', include('django_ckeditor_5.urls')),
    path('select2/', include('django_select2.urls')),
]
if settings.DEBUG:
    # add root static files
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # add media static files
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'kheylisadas.views.custom_page_not_found_view_404'
handler500 = 'kheylisadas.views.custom_error_view_500'
handler403 = 'kheylisadas.views.custom_permission_denied_view_403'
handler400 = 'kheylisadas.views.custom_bad_request_view_400'

ks_article/urls.py
from django.urls import path

from ks_article.views import ArticlesList, ArticlesListByCategory, articles_categories_partial, \
    ArticleDetailView, add_article_comment, articles_all_tags_partial, ArticlesListByTag, recent_articles_partial

urlpatterns = [
    path('', ArticlesList.as_view() , name='articles_list'),
    path('<slug:category_slug>/', ArticlesListByCategory.as_view(), name='articles_list_by_category'),
    path('tag/<slug:slug>/', ArticlesListByTag.as_view(), name='articles_list_by_tag'),
    path('<int:pk>/<slug:slug>', ArticleDetailView.as_view(), name='article_detail'),

    path('article_categories_partial', articles_categories_partial, name='articles_categories_partial'),
    path('recent-articles-partial', recent_articles_partial, name='recent_articles_partial'),
    path('articles_all_tags_partial', articles_all_tags_partial, name='articles_all_tags_partial'),
    path('add-article-comment', add_article_comment, name='add_article_comment')
]

ks_article/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.text import slugify
from PIL import Image
from django_ckeditor_5.fields import CKEditor5Field

from ks_account.models import User
from ks_audio.models import AudioArticle
from ks_course.models import Course
from ks_site.models import AgeCategory
from ks_tag.models import Tag
from utility.choices import KSChoices
from utility.utils import upload_articles_category_image_path, upload_articles_image_path


class ArticleCategoriesManager(models.Manager):
    def get_active_categories(self):
        return self.get_queryset().filter(is_active=True)



class ArticlesManager(models.Manager):
    def get_active_articles(self):
        return self.get_queryset().filter(is_active=True)

    def get_articles_by_category_id(self, category_id):
        return self.get_queryset().filter(category_id=category_id, is_active=True)

    def get_by_id(self, article_id):
        qs = self.get_queryset().filter(id=article_id, is_active=True)
        if qs.count() == 1:
            return qs.first()
        else:
            return None

    # def search(self, query):
    #     lookup = (
    #             Q(title__icontains=query) |
    #             Q(description__icontains=query) |
    #             Q(tag__title__icontains=query)
    #     )
    #     return self.get_queryset().filter(lookup, active=True).distinct()


# Create your models here.
class ArticleCategory(models.Model):
    title = models.CharField(max_length=150)
    name = models.CharField(max_length=150)
    # thumb = models.ImageField(upload_to=upload_articles_category_image_path, null=True, blank=True)
    image = models.ImageField(upload_to=upload_articles_category_image_path, null=True, blank=True)
    is_active = models.BooleanField(default=False)
    is_delete = models.BooleanField(default=False)
    description = models.TextField(null=True, blank=True)
    create_date = models.DateTimeField(default=timezone.now, editable=False)
    slug = models.SlugField(default="", blank='True', null=True,
                            db_index=True)  # samsung galaxy s 20 => samsung-galaxy-s-20
    objects = ArticleCategoriesManager()

    def get_count(self):
        return self.article_set.all().count()

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)


    # class Meta:
    #     verbose_name = 'دسته بندی'
    #     verbose_name_plural = 'دسته بندی ها'

    def __str__(self):
        return self.name


class Article(models.Model):
    category = models.ForeignKey(ArticleCategory, on_delete=models.CASCADE)
    title = models.CharField(max_length=150, null=True, blank=True)
    name = models.CharField(max_length=150, null=True, blank=True)
    is_active = models.BooleanField(default=False)
    is_delete = models.BooleanField(default=False)
    image = models.ImageField(upload_to=upload_articles_image_path, null=True, blank=True)
    description = models.TextField(null=True)
    description_rich = CKEditor5Field('Description', config_name='default', null=True, blank=True)
    alt_image = models.TextField(null=True, blank=True, max_length=100)
    create_date = models.DateTimeField(default=timezone.now, editable=False)
    slug = models.SlugField(default="", blank='True', null=True,
                            db_index=True)  # samsung galaxy s 20 => samsung-galaxy-s-20
    tags = models.ManyToManyField(Tag, blank=True)
    courses = models.ManyToManyField(Course, blank=True)
    audios = models.ManyToManyField(AudioArticle, blank=True)
    age_category = models.ForeignKey(AgeCategory, on_delete=models.CASCADE, null=True, blank=True)
    fake_visit_count = models.IntegerField(default=5)
    fake_like_count = models.IntegerField(default=5)
    fake_dislike_count = models.IntegerField(default=5)


    objects = ArticlesManager()

    def get_absolute_url(self):
        return reverse('article_detail', args=[self.id, self.slug])

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    # class Meta:
    #     verbose_name = 'فصل دسته'
    #     verbose_name_plural = 'فصل دسته ها'

    def __str__(self):
        return self.title

class ArticleComment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    parent = models.ForeignKey('ArticleComment', null=True, blank=True, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    create_date = models.DateTimeField(default=timezone.now)
    text = models.TextField()
    is_allowed = models.BooleanField(default=False)


    def __str__(self):
        return str(self.user)


class ArticleVisit(models.Model):
    article = models.ForeignKey('Article', on_delete=models.CASCADE)
    ip = models.CharField(max_length=30)
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)
    create_date = models.DateTimeField(default=timezone.now, editable=False)

    def __str__(self):
        return f'{self.article.title} / {self.ip}'

ks_article/templates/includes/article_categories_partial.html
<div class="single_widgets widget_category">
    <h4 class="title">دسته بندی ها</h4>
    <ul>
        <li><a href="/articles">همه </a> </li>
        {% for category in categories %}
            <li>
{#                <a href="/articles/{{ category.id }}/{{ category.slug }}">#}
                <a href="{% url 'articles_list_by_category' category_slug=category.slug %}">
                    {{ category.name }}
                    <span>{{ category.get_count }}</span>
                </a>
            </li>
        {% endfor %}

    </ul>
</div>

ks_article/templates/includes/articles_all_tags_partial.html
<div class="single_widgets widget_tags">
    <h4 class="title">برچسب ها</h4>
    <ul>
        {% for tag in tags %}
{#            <li><a href="/articles/tag/{{ tag.slug }}"> {{ tag.title }} </a></li>#}
            <li><a href="{% url 'articles_list_by_tag' slug=tag.slug %}"> {{ tag.title }} </a></li>
        {% endfor %}
    </ul>
</div>

ks_article/templates/includes/comments_partial.html
{% load thumbnail %}
{% load jalali_tags %}
{% load static %}
{% load poll_extras %}

<div class="list-single-main-item-title fl-wrap">
    <h3>{{ comments_count }} نظر </h3>
</div>
<hr>
<div>
    <ul>
        {% for comment in comments %}
            <li class="reviews-comments-item" id="single_comment_box_{{ comment.id }}">
                {#  comment#}
                <article>
                    <div class="review-comments-avatar">
                        {% if comment.user.is_superuser %}
                            {% thumbnail avatar.avatar_admin "x120" quality=90 as im %}
                                <img src="{{ im.url }}" class="img-fluid avater" alt="{{ comment.user.username }}">

                            {% endthumbnail %}
                        {% elif comment.user.is_staff %}
                            {% thumbnail avatar.avatar_staff "x120" quality=90 as im %}
                                <img src="{{ im.url }}" class="img-fluid avater" alt="{{ comment.user.username }}">

                            {% endthumbnail %}
                        {% else %}
                            {% thumbnail avatar.avatar "x120" quality=90 as im %}
                                <img src="{{ im.url }}" class="img-fluid avater" alt="{{ comment.user.username }}">
                            {% endthumbnail %}
                        {% endif %}
                    </div>
                    <div class="reviews-comments-item-text">
                        <h4><a href="#">{{ comment.user }}</a>
                            <span class="reviews-comments-item-date">
                                <i class="ti-calendar ml-2"> <span class=" ml-2">
                                                            {{ comment.create_date|to_jalali:'%d %B %Y' }}
                                                            {% comment %}{{ comment.create_date|to_jalali:'%B' }}
                                                            {{ comment.create_date|to_jalali:'%Y' }}{% endcomment %}
                                                        </span> </i>
{#                                <i class="ti-calendar ml-2"> {{ comment.create_date|show_jalali_date }} </i>#}
                                <i class="ti-alarm-clock ml-2"> {{ comment.create_date | time }}   </i>
                            </span>
                        </h4>

                        <div class="clearfix"></div>
                        <p> {{ comment.text }} </p>
                        <div class="align-to-right reviews-reaction">
                            {#                                                            <a href="#" class="comment-like active"><i#}
                            {#                                                                    class="ti-thumb-up"></i> 12</a>#}
                            {#                                                            <a href="#" class="comment-dislike active"><i#}
                            {#                                                                    class="ti-thumb-down"></i> 1</a>#}
                            <a class="btn" onclick="fillParentId({{ comment.id }})">
                                                                <span class="icona">
                                                                    <i class="ti-back-right"></i>
                                                                </span> پاسخ
                            </a>
                        </div>
                    </div>
                </article>
                <ul>
                    {% for sub_comment in comment.articlecomment_set.all %}
                        <li class="reviews-comments-item"
                            id="single_comment_box_{{ comment.id }}">
                            {#  sub commnet#}
                            <article>
                                <div class="review-comments-avatar">
                                    {% if sub_comment.user.is_superuser %}
                                        {% thumbnail avatar.avatar_admin "x120" quality=90 as im %}
                                            <img src="{{ im.url }}" class="img-fluid avater"
                                                 alt="{{ sub_comment.user.username }}">

                                        {% endthumbnail %}
                                    {% elif sub_comment.user.is_staff %}
                                        {% thumbnail avatar.avatar_staff "x120" quality=90 as im %}
                                            <img src="{{ im.url }}" class="img-fluid avater"
                                                 alt="{{ sub_comment.user.username }}">

                                        {% endthumbnail %}
                                    {% else %}
                                        {% thumbnail avatar.avatar "x120" quality=90 as im %}
                                            <img src="{{ im.url }}" class="img-fluid avater"
                                                 alt="{{ sub_comment.user.username }}">
                                        {% endthumbnail %}
                                    {% endif %}

                                </div>
                                <div class="reviews-comments-item-text">
                                    <h4><a href="#">{{ sub_comment.user }}</a>
                                        <span class="reviews-comments-item-date">
                                                                        <i class="ti-calendar ml-2">
                                                                            <span class=" ml-2">
                                                                                {{ sub_comment.create_date|to_jalali:'%d' }}
                                                                                {{ sub_comment.create_date|to_jalali:'%B' }}
                                                                                {{ sub_comment.create_date|to_jalali:'%Y' }}
                                                                            </span>
                                                                        </i>
                                                                        <i class="ti-alarm-clock ml-2"> {{ sub_comment.create_date | time }} </i>
                                                                    </span>
                                    </h4>

                                    <div class="clearfix"></div>
                                    <p> {{ sub_comment.text }} </p>
                                    {#                                                                    <div class="align-to-left reviews-reaction">#}
                                    {#                                                                        <a href="#" class="comment-like active"><i#}
                                    {#                                                                                class="ti-thumb-up"></i> 12</a>#}
                                    {#                                                                        <a href="#" class="comment-dislike active"><i#}
                                    {#                                                                                class="ti-thumb-down"></i> 1</a>#}
                                    {#                                                                    </div>#}
                                </div>
                            </article>

                        </li>
                    {% endfor %}
                </ul>
            </li>
        {% endfor %}
    </ul>
</div>

ks_article/templates/includes/recent_articles_partial.html
{% load thumbnail %}
{% load sorl_thumbnail %}
{% load poll_extras %}
<div class="single_widgets widget_thumb_post">
    <h4 class="title"> مقالات اخیر </h4>
    <ul>
        {% for article in articles %}
            <li>
                <a href="{{ article.get_absolute_url }}">
                    <span class="left">
                        {% thumbnail article.image "128" quality=90 as im %}
                            <img src="{{ im.url }}" class="img-fluid corner-radius" alt="{{ article.alt_image }}">

                        {% endthumbnail %}
                    </span>
                </a>
                <span class="right">
                    <a class="feed-title"
                       href="{{ article.get_absolute_url }}"> {{ article.name }} </a>
                    <span class="post-date"><i
                            class="ti-calendar"></i>{{ article.create_date|show_jalali_date }}</span>
                </span>
            </li>
        {% endfor %}


    </ul>
</div>

ks_article/templates/includes/related_courses_partial.html
{% load smooth_timedelta %}
{% load thumbnail %}
{% load sorl_thumbnail %}
{% load poll_extras %}
<div class="single_widgets widget_thumb_post">
    <h4 class="title"> دوره های مرتبط برای یادگیری بیشتر </h4>
    <ul>
        {% for course in related_courses %}
            <li>
                <a href="{{ course.get_absolute_url }}">
                    <span class="left">
                        {% thumbnail course.image "128" quality=90 as im %}
                            <img src="{{ im.url }}" class="img-fluid corner-radius" alt="{{ course.alt_image }}">

                        {% endthumbnail %}
                    </span>
                </a>
                <span class="right">
                    <a class="feed-title"
                       href="{{ course.get_absolute_url }}"> {{ course.name }} </a>
                    <span class="course-duration">

                        <i class="ti-time"></i>
                        <strong>
                            {% comment %}{{ course.audios_duration|time:"H:i" }}{% endcomment %}
                            {{ course.audios_duration|smooth_timedelta }}
                        </strong>
                    </span>
                </span>
            </li>
        {% endfor %}


    </ul>
</div>