core/urls.py
from django.urls import path

from core.views import index

urlpatterns = [
    path('', index, name='index')
]

kheylisadas/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from kheylisadas import settings
from .views import home_page, header, footer, index_page, success_page, failure_page, maintenance_view, service_worker, \
    manifest_version, check_login_status

urlpatterns = [
    path('maintenance/', maintenance_view, name='maintenance'),
    # path('index', index_page, name="home_page"),
    path('', home_page, name="home_page"),
    path('index', home_page, name="home_page"),
    path('success', success_page, name="success_page"),
    path('failure', failure_page, name="failure_page"),
    path('service-worker/', service_worker, name='service-worker'),
    path('manifest-version/', manifest_version, name='manifest_version'),
    path('check-login-status/', check_login_status, name='check_login_status'),

    path('', include('ks_account.urls')),
    path('', include('ks_category.urls')),
    path('audio/', include('ks_audio.urls')),
    path('courses/', include('ks_course.urls')),
    path('articles/', include('ks_article.urls')),
    path('subscription/', include('ks_subscription.urls')),
    path('votes/', include('ks_vote.urls')),
    path('user/', include('ks_user_panel.urls')),
    path('', include('ks_site.urls')),
    path('header', header, name="header"),
    path('footer', footer, name="footer"),
    path('ks-admin-panel/', admin.site.urls),
    path('ks-account/', include(('ks_account.urls', 'ks_account'), namespace='ks_account')), # اضافه کردن namespace
    # path('admin/', admin.site.urls),
    path('core/', include('core.urls')),  # for webpack
    path('captcha/', include('captcha.urls')),  # capthca urls
    # path('ckeditor/', include('ckeditor_uploader.urls')),  # ckeditor uploader urls
    path('ckeditor/', include('django_ckeditor_5.urls')),
    path('select2/', include('django_select2.urls')),
]
if settings.DEBUG:
    # add root static files
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # add media static files
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'kheylisadas.views.custom_page_not_found_view_404'
handler500 = 'kheylisadas.views.custom_error_view_500'
handler403 = 'kheylisadas.views.custom_permission_denied_view_403'
handler400 = 'kheylisadas.views.custom_bad_request_view_400'

ks_course/urls.py
from django.urls import path
from . import views
from .views import CoursesListView, CourseDetailView, add_course_comment, CoursePriceDetailView, \
    course_request_payment, \
    course_verify_payment, course_free_gift

urlpatterns = [
    path('', CoursesListView.as_view(), name='courses_list'),
    path('<int:pk>/<slug:slug>', CourseDetailView.as_view(), name='course_detail'),
    path('add-course-comment', add_course_comment, name='add_course_comment'),

    path('course-price/<int:pk>/<slug:slug>', CoursePriceDetailView.as_view(), name='course_price_detail'),
    path('course-free-gift/<int:course_id>/<str:code>', course_free_gift, name='course_free_gift'),
    path('course-request-payment/<int:course_id>/<str:code>', course_request_payment, name='course_request_payment'),
    path('course-verify-payment/', course_verify_payment, name='course_verify_payment')

]

ks_course/models.py
import time

from django.contrib.auth.models import Group
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.text import slugify

import ks_audio
from ks_account.models import User
from ks_site.models import AgeCategory
from ks_subscription.models import Payment
from ks_tag.models import Tag
from utility.choices import KSChoices
from utility.utils import upload_course_image_path, group_course_name


# class CourseManager(models.Manager):
#     def get_audio_count(self):
#         audio_count = 0
#         sections_course = SectionCourse.objects.filter(course_id=self.id, is_active=True)
#         for section in sections_course:
#             audios = AudioCourse.objects.filter(section_course_id=section.id, is_active=True)
#             audio_count += audios.count()
#         return audio_count
#         return self.get_queryset().filter(is_active=True)

class Course(models.Model):
    title = models.CharField(max_length=150, null=True, blank=True)
    name = models.CharField(max_length=150, null=True, blank=True)
    fake_price = models.IntegerField(null=True, blank=True)
    price = models.IntegerField(null=False, blank=False)
    off_price = models.IntegerField(null=True, blank=True)
    off = models.IntegerField(null=True, blank=True)
    is_active = models.BooleanField(default=False)
    is_delete = models.BooleanField(default=False)
    icon = models.CharField(default='A', max_length=10)
    thumb = models.ImageField(upload_to=upload_course_image_path, null=True, blank=True)
    image = models.ImageField(upload_to=upload_course_image_path, null=False, blank=False)
    alt_image = models.TextField(null=True, blank=True, max_length=100)
    description = models.TextField(null=True)
    create_date = models.DateTimeField(default=timezone.now, editable=False)
    slug = models.SlugField(default="", blank='True', null=True,
                            db_index=True)  # samsung galaxy s 20 => samsung-galaxy-s-20
    tags = models.ManyToManyField(Tag, blank=True)
    age_category = models.ForeignKey(AgeCategory, on_delete=models.CASCADE, null=True, blank=True)
    has_practice = models.BooleanField(default=False)
    last_update = models.DateTimeField(default=timezone.now, editable=True)
    fake_visit_count = models.IntegerField(default=5)
    fake_students_count = models.IntegerField(default=25)
    fake_like_count = models.IntegerField(default=5)
    fake_dislike_count = models.IntegerField(default=5)

    class Meta:
        permissions = (
            ('fully_view_course', 'Can fully view course'),
        )
        get_latest_by = 'create_date'


    def get_absolute_url(self):
        return reverse('course_detail', args=[self.id, self.slug])

    def get_absolute_url_price(self):
        return reverse('course_price_detail', args=[self.id, self.slug])

    @property
    def audio_count(self):
        audio_count = 0
        sections_course = SectionCourse.objects.filter(course_id=self.id, is_active=True)
        for section in sections_course:
            audio_count += section.section_audio_count
        return audio_count

    @property
    def audios_duration(self):
        duration = timezone.timedelta(0)
        for section in SectionCourse.objects.filter(course_id=self.id, is_active=True):
            duration += section.section_audio_duration
        # print(type(duration))
        return duration

    @property
    def students(self):
        return Group.objects.filter(name=group_course_name(self.title)).count()

    def price_1000(self):
        return int(self.price / 1000)

    def fake_price_1000(self):
        if self.fake_price:
            return int(self.fake_price / 1000)
        else:
            return 0

    def price_off_1000(self):
        return int(self.price / 1000)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    # class Meta:
    #     verbose_name = 'فصل دسته'
    #     verbose_name_plural = 'فصل دسته ها'

    def __str__(self):
        return self.name

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # self.set_off_price = kwargs.get('set_off_price', list)
        self.off_price = None

    @property
    def set_off_price(self):
        return self.off_price

    @set_off_price.setter
    def set_off_price(self, values):  # 0 is percent and 1 is max
        percent, max_off = values
        off = self.price * percent / 100
        if off > max_off:
            off = max_off

        if int(self.price - off) < 0:
            self.off_price = 0
            self.off = int(self.price)
        else:
            self.off = int(off)
            self.off_price = int(self.price - off)


class SectionCourse(models.Model):
    title = models.CharField(max_length=150)
    name = models.CharField(max_length=150)
    is_active = models.BooleanField(default=False)
    is_delete = models.BooleanField(default=False)
    description = models.TextField(null=True, blank=True)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.name} / {self.course}"

    @property
    def section_audio_count(self):
        return ks_audio.models.AudioCourse.objects.filter(section_course_id=self.id, is_active=True).count()

    @property
    def section_audio_duration(self):
        duration = timezone.timedelta(0)
        for audio in ks_audio.models.AudioCourse.objects.filter(section_course_id=self.id, is_active=True):
            duration += audio.duration
        return duration


class CourseComment(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    parent = models.ForeignKey('CourseComment', null=True, blank=True, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    create_date = models.DateTimeField(default=timezone.now)
    text = models.TextField()
    is_allowed = models.BooleanField(default=False)

    def __str__(self):
        return str(self.user)


class CourseVisit(models.Model):
    course = models.ForeignKey('Course', on_delete=models.CASCADE)
    ip = models.CharField(max_length=30)
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.course.title} / {self.ip}'


class TransactionCourse(models.Model):
    BEFORE_PAYMENT = 1
    ERROR_BEFORE_PAYMENT = 2
    SUCCESS_PAYMENT = 3
    STATUS_CHOICES = (
        (BEFORE_PAYMENT, 'قبل از پرداخت',),
        (ERROR_BEFORE_PAYMENT, 'خطا - قبل از پرداخت',),
        (SUCCESS_PAYMENT, 'پرداخت موفق',),
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    payment = models.ForeignKey(Payment, on_delete=models.CASCADE, null=True, blank=True)
    create_date = models.DateTimeField(default=timezone.now, null=False, blank=False)
    try_date = models.DateTimeField(default=timezone.now, null=False, blank=False)
    # start_date = models.DateTimeField(null=True, blank=True)
    # end_date = models.DateTimeField(null=True, blank=True)
    is_paid = models.BooleanField(default=False)
    in_process = models.BooleanField(default=False)
    status = models.IntegerField(choices=STATUS_CHOICES, null=True, blank=True, default=1)
    info = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return f"کاربر: {self.user.__str__()} دوره: {self.course.__str__()}"


class GiftCourse(models.Model):
    code = models.CharField(max_length=10, unique=True, help_text="Enter the gift code")
    percentage = models.PositiveSmallIntegerField(help_text="Enter the discount percentage (e.g., 10 for 10%)")
    max = models.IntegerField(null=True, blank=True)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    is_active = models.BooleanField(default=True)
    is_expired = models.BooleanField(default=False)
    start_date = models.DateField(default=timezone.now, null=True, blank=True,
                                  help_text="Enter the start date of the discount code")
    end_date = models.DateField(null=True, blank=True, help_text="Enter the end date of the discount code")

    def __str__(self):
        return self.code

    @property
    def is_expired_this(self):
        if self.end_date < timezone.now():
            self.is_expired = True
            self.save()
            return True
        return False

ks_course/templates/components/course_card_component.html
{% load smooth_timedelta %}
{% load thumbnail %}
<div class="col-lg-4 col-md-6">
    <div class="education_block_grid style_2 {% if courses_is_disabled %}disabled-card{% endif %}">
        <div class="education_block_thumb n-shadow">
            {% if not courses_is_disabled %}
                <a href="{{ course.get_absolute_url }}">
            {% endif %}
            {% thumbnail course.image "400" quality=90 as im %}
                <img src="{{ im.url }}" class="img-fluid corner-radius full-width" alt="{{ course.alt_image }}">
            {% endthumbnail %}
            {% if not courses_is_disabled %}
                </a>
            {% endif %}
            {% if request.user.is_staff %}
                <div class="number_visits_real"><i class="fa fa-eye"></i>
                    {{ course.coursevisit_set.count }}
                </div>
            {% endif %}

            <div class="number_visits"><i class="fa fa-eye"></i>
                {{ course.coursevisit_set.count|add:course.fake_visit_count }}
            </div>
        </div>

        <div class="education_block_body">
            <h4 class="bl-title">
                {% if not courses_is_disabled %}
                    <a href="{{ course.get_absolute_url }}">
                {% endif %}
                دوره {{ course.name }}
                {% if not courses_is_disabled %}
                    </a>
                {% endif %}
            </h4>
        </div>

        <div class="courses_info_style3">
            <ul>
                <li class="audio_count">
                    <div class="foot_features">
                        <i class="ti-headphone"></i>
                        {{ course.audio_count }}
                    </div>
                </li>
                <li class="duration">
                    <div class="foot_features">
                        <i class="ti-timer"></i>
                        {{ course.audios_duration|smooth_timedelta }}
                    </div>
                </li>
            </ul>
        </div>
        {% if not courses_is_disabled %}
            <div class="price_block_footer">
                <div class="foot_price_off">
                    <span class="sg_rate theme-cl price_off"><del><strong>{{ course.fake_price_1000 }}</strong> هزار تومان</del></span>
                </div>
                <div class="foot_lecture">

                    <a href="{{ course.get_absolute_url }}">
                        <span class="sg_rate foot_price"><strong>{{ course.price_1000 }}</strong> هزار تومان</span>
                    </a>

                </div>
            </div>
        {% endif %}
    </div>
</div>

ks_course/templates/components/course_card_component_for_panel.html
{% load smooth_timedelta %}
{% load thumbnail %}
<div class="col-lg-4 col-md-6">
    <div class="education_block_grid style_2">
        <div class="education_block_thumb n-shadow">
            <a href="{{ course.get_absolute_url }}">
                {% thumbnail course.image "400" quality=90 as im %}
                    <img src="{{ im.url }}" class="img-fluid corner-radius full-width" alt="{{ course.alt_image }}">
                {% endthumbnail %}
            </a>
        </div>

        <div class="education_block_body">
            <h4 class="bl-title"><a href="{{ course.get_absolute_url }}">دوره {{ course.name }}</a></h4>
        </div>

        <div class="courses_info_style3 ">
            <ul>
{#                <li>#}
{#                    <i class="ti-eye ml-2"></i>{{ course.coursevisit_set.count|add:course.fake_visit_count }}#}
{#                </li>#}
                <li class="audio_count">
                    <div class="foot_features ">
                            <i class="ti-headphone  "></i>
                            {{ course.audio_count }}
                    </div>
                </li>
                <li class="duration">
                    <div class="foot_features ">
                            <i class="ti-timer  "></i>

                            {{ course.audios_duration|smooth_timedelta  }}
                    </div>
{#                    <i class="ti-time ml-2 duration"></i>{{ course.audios_duration|smooth_timedelta  }}#}
                </li>
            </ul>
        </div>

        {% comment %}<div class="education_block_footer">

            <div class="foot_lecture">
                <a href="{{ course.get_absolute_url }}">

                    <i class="ti-headphone ml-2"></i>
                    {{ course.audio_count }}
                </a>

            </div>
        </div>{% endcomment %}
    </div>
</div>